# -*- coding: utf-8 -*-
"""piloting analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTSVTI0CydvlGZlg9KBloUaOGWjIt3-r
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.optimize import curve_fit
import glob
from scipy.stats import norm

sns.set_theme(style="whitegrid", context="paper", font_scale=1.2)

file_pattern = "data_p*_session_*.csv"
file_list = glob.glob(file_pattern)

df_list = []
for file in file_list:
    temp_df = pd.read_csv(file)
    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index=True)

df['is_correct'] = df['response_numeric']
df['abs_offset'] = df['offset'].abs()

def psychometric_accuracy(x, alpha, beta):
    #yhat=0.5 + (0.5-gamma) / (1 + np.exp(-beta * (x - alpha)))
    yhat=(norm.cdf(x,0,alpha)-0.5)*(1-beta)+0.5
    return yhat

blocks = df['label'].unique()

fig, axes = plt.subplots(2, 2, figsize=(14, 10), sharey=True)
axes_flat = axes.flatten()
colors = sns.color_palette("deep", len(blocks))

for i, (ax, block, color) in enumerate(zip(axes_flat, blocks, colors)):
    block_data = df[df['label'] == block]

    summary = block_data.groupby('abs_offset')['is_correct'].agg(
        prob_correct='mean',
        trial_count='count'
    ).reset_index()

    x = summary['abs_offset'].values
    y = summary['prob_correct'].values
    sizes = summary['trial_count'].values


    #CURVE FIT
    p0 = [0.1,0.1]
    try:
        #x=np.array((0,)+tuple(x))
        #y=np.array((0.5,)+tuple(y))
        #sizes=np.array((100000,)+tuple(sizes))
        w=1/sizes
        #print(y.shape)
        #w=np.ones(len(x))/1
        #w[0]=0.01

        popt, _ = curve_fit(psychometric_accuracy, x, y, sigma=w, p0=p0, maxfev=10000)
        alpha, beta = popt
    except RuntimeError:
        alpha, beta = np.mean(x), 1

    jnd_75 = alpha

    sns.scatterplot(
        x=x, y=y,size=sizes,
        color=color, alpha=0.8, ax=ax, edgecolor="black", legend=False
    )

    x_smooth = np.linspace(0, x.max() * 1.1, 300)
    y_smooth = psychometric_accuracy(x_smooth, alpha, beta)

    ax.plot(x_smooth, y_smooth, color=color, linewidth=3,
            label=f"75% JND = {jnd_75:.3f}\nSlope (β) = {beta:.1f}")

    ax.axhline(0.75, color='gray', linestyle='--', alpha=0.6)
    ax.axvline(jnd_75, color='gray', linestyle='--', alpha=0.6)

    ax.set_title(block, fontsize=14, fontweight='bold', pad=10)
    ax.set_xlabel("Absolute Offset", fontsize=12)
    ax.set_ylabel("Accuracy", fontsize=12)
    ax.legend(loc="lower right", frameon=True, shadow=True)
    ax.set_ylim(0.45, 1.05)

sns.despine()
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import glob
import os
from scipy.optimize import curve_fit
from scipy.stats import norm

def psychometric_accuracy(x, alpha, beta):
    yhat = (norm.cdf(x, 0, alpha) - 0.5) * (1 - beta) + 0.5
    return yhat

file_list = glob.glob('data_p*_session_*.csv')
file_list = [f for f in file_list if '(' not in f and '_parameters.csv' not in f]

all_results = []

for file in file_list:
    filename = os.path.basename(file)
    participant_id = filename.split('_')[1]
    indv_df = pd.read_csv(file)

    indv_df['is_correct'] = indv_df['response_numeric']
    indv_df['abs_offset'] = indv_df['offset'].abs()

    # Temporary dictionary to store JNDs (alpha) for this specific file
    jnds_for_file = {}

    # Loop through each unique block to get the JNDs
    for block_label in indv_df['label'].unique():
        block_data = indv_df[indv_df['label'] == block_label]

        summary = block_data.groupby('abs_offset')['is_correct'].agg(
            prob_correct='mean',
            trial_count='count'
        ).reset_index()

        x = summary['abs_offset'].values
        y = summary['prob_correct'].values
        sizes = summary['trial_count'].values

        alpha, beta = np.nan, np.nan

        # Only proceed if there's enough data for curve_fit
        if len(x) >= 2 and len(np.unique(y)) >= 2:
            p0 = [0.1, 0.1]
            try:
                w = 1 / sizes
                w[~np.isfinite(w)] = 0 # Set weights for 0-trial points to 0

                popt, _ = curve_fit(psychometric_accuracy, x, y, sigma=w, p0=p0, maxfev=10000)
                alpha, beta = popt
            except (RuntimeError, ValueError):
                pass # If it fails, alpha remains NaN

        # Save the calculated alpha (JND) to our dictionary under the block label
        jnds_for_file[block_label] = alpha

    # Safely extract the JNDs by checking if the label contains our target strings
    b_standard = next((v for k, v in jnds_for_file.items() if 'Binocular_Standard' in str(k)), np.nan)
    b_crowded = next((v for k, v in jnds_for_file.items() if 'Binocular_Crowded' in str(k)), np.nan)
    m_standard = next((v for k, v in jnds_for_file.items() if 'Monocular_Standard' in str(k)), np.nan)
    m_crowded = next((v for k, v in jnds_for_file.items() if 'Monocular_Crowded' in str(k)), np.nan)

    # Calculate Ratios (Crowded / Standard). Ensure we don't divide by zero or NaN.
    ratio_binocular = np.nan
    if pd.notna(b_standard) and b_standard != 0 and pd.notna(b_crowded):
        ratio_binocular = b_crowded / b_standard

    ratio_monocular = np.nan
    if pd.notna(m_standard) and m_standard != 0 and pd.notna(m_crowded):
        ratio_monocular = m_crowded / m_standard

    # Append to our master list
    all_results.append({
        'participant_file': filename,
        'participant_id': participant_id,
        'JND_Binocular_Standard': b_standard,
        'JND_Binocular_Crowded': b_crowded,
        'Ratio_Binocular': ratio_binocular,
        'JND_Monocular_Standard': m_standard,
        'JND_Monocular_Crowded': m_crowded,
        'Ratio_Monocular': ratio_monocular
    })

# Convert to DataFrame
final_df = pd.DataFrame(all_results)

# Average the results per participant (in case there are multiple sessions/files per participant)
final_avg_per_participant = final_df.groupby('participant_id').mean(numeric_only=True).reset_index()

print("\n--- Final Ratios and JNDs per Participant ---")
print(final_avg_per_participant.to_string())

import pandas as pd
import numpy as np
import glob
import os
from scipy.optimize import curve_fit
from scipy.stats import norm

# Make sure your psychometric function is defined if running this block separately
def psychometric_accuracy(x, alpha, beta):
    return (norm.cdf(x, 0, alpha) - 0.5) * (1 - beta) + 0.5

# Re-filter file list to exclude parameters
file_list = glob.glob('data_p*_session_*.csv')
file_list = [f for f in file_list if '(' not in f and '_parameters.csv' not in f]

all_jnd_results = []       # Stores block-level alphas
participant_ratios = []    # Stores participant-level ratios calculated from alphas

for file in file_list:
    filename = os.path.basename(file)
    participant_id = filename.split('_')[1]
    indv_df = pd.read_csv(file)

    indv_df['is_correct'] = indv_df['response_numeric']
    indv_df['abs_offset'] = indv_df['offset'].abs()

    # Dictionary to hold the alphas for the current participant
    current_alphas = {}

    # 1. Loop through blocks and calculate Alpha (JND) first
    for block_label in indv_df['label'].unique():
        block_data = indv_df[indv_df['label'] == block_label]

        summary = block_data.groupby('abs_offset')['is_correct'].agg(
            prob_correct='mean',
            trial_count='count'
        ).reset_index()

        x = summary['abs_offset'].values
        y = summary['prob_correct'].values
        sizes = summary['trial_count'].values

        alpha, beta = np.nan, np.nan

        # Check if we have enough data to fit the curve
        if len(x) >= 2 and len(np.unique(y)) >= 2:
            p0 = [0.1, 0.1]
            try:
                w = 1 / sizes
                w[~np.isfinite(w)] = 0
                popt, pcov = curve_fit(psychometric_accuracy, x, y, sigma=w, p0=p0, maxfev=10000)
                alpha, beta = popt
            except (RuntimeError, ValueError):
                pass # Leaves alpha as np.nan

        # Store the alpha in our temporary dictionary and the master list
        current_alphas[block_label] = alpha

        all_jnd_results.append({
            'participant_file': filename,
            'participant_id': participant_id,
            'block_label': block_label,
            'jnd_alpha': alpha,
        })

    # 2. Calculate Ratios from the computed Alphas
    # Extract the specific alphas needed for this participant.
    # Using 'in' just in case the label strings have trailing numbers (e.g., 'Binocular_Standard_1')
    alpha_bin_std = next((v for k, v in current_alphas.items() if 'Binocular_Standard' in k), np.nan)
    alpha_bin_crw = next((v for k, v in current_alphas.items() if 'Binocular_Crowded' in k), np.nan)
    alpha_mon_std = next((v for k, v in current_alphas.items() if 'Monocular_Standard' in k), np.nan)
    alpha_mon_crw = next((v for k, v in current_alphas.items() if 'Monocular_Crowded' in k), np.nan)

    # Binocular Ratio (Crowded / Standard)
    ratio_bin = np.nan
    if pd.notna(alpha_bin_std) and pd.notna(alpha_bin_crw) and alpha_bin_std != 0:
        logratio_bin = np.log(alpha_bin_crw / alpha_bin_std)

    # Monocular Ratio (Crowded / Standard)
    ratio_mon = np.nan
    if pd.notna(alpha_mon_std) and pd.notna(alpha_mon_crw) and alpha_mon_std != 0:
        logratio_mon =np.log(alpha_mon_crw / alpha_mon_std)

    # Store final ratios for this participant
    participant_ratios.append({
        'participant_id': participant_id,
        'alpha_binocular_standard': alpha_bin_std,
        'alpha_binocular_crowded': alpha_bin_crw,
        'logratio_binocular': logratio_bin,
        'alpha_monocular_standard': alpha_mon_std,
        'alpha_monocular_crowded': alpha_mon_crw,
        'logratio_monocular': logratio_mon
    })

# --- Final Aggregations ---

# 1. Block-level JNDs (averaged in case a participant did the same session twice)
final_jnd_df = pd.DataFrame(all_jnd_results)
final_jnd_avg_per_participant = final_jnd_df.groupby(['participant_id', 'block_label']).mean(numeric_only=True).reset_index()

# 2. Participant-level Ratios (averaged in case of multiple files per participant)
final_ratios_df = pd.DataFrame(participant_ratios)
final_ratios_avg_per_participant = final_ratios_df.groupby('participant_id').mean(numeric_only=True).reset_index()

print("\n--- JND (alpha) results per participant and block ---")
print(final_jnd_avg_per_participant.to_string())

print("\n--- Binocular and Monocular Ratios (calculated from Alphas) ---")
print(final_ratios_avg_per_participant.to_string())
df = pd.merge(final_results_df_monocular, final_results_df_binocular, on='participant_id', suffixes=('_m', '_b'))
lim = 2
fig, ax = plt.subplots(figsize=(7, 6))

ax.scatter(np.log(df['ratio_m']), np.log(df['ratio_b']), s=150, c='lightblue')

ax.plot([-lim, lim], [-lim, lim], color='gray', linestyle='--', label='y = x', zorder=1)
ax.set(xlim=(-lim, lim), ylim=(-lim, lim), xlabel='Log(Monocular Ratio)', ylabel='Log(Binocular Ratio)', title='Threshold Ratios: Binocular vs Monocular')
ax.grid(True, linestyle=':', alpha=0.7)
ax.legend(loc='upper left')

plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from scipy.stats import norm
import psignifit as ps

res = ps.psignifit(data, sigmoid='norm', experiment_type='2AFC')

df = pd.read_csv('data_p11_session_01.csv')

# 2. Psychometric Function Setup
def psychometric_curve(x, mu, sigma):
    return norm.cdf(x, loc=mu, scale=sigma)

plt.figure(figsize=(10, 6))
print("--- Psychometric Function Fit Results ---")


for label, group in df.groupby('label'):
    summary = group.groupby('offset')['keys'].apply(
        lambda x: x.astype(str).str.contains('right').mean()
    ).reset_index(name='prob_right')

    x_data = summary['offset']
    y_data = summary['prob_right']

    # Fit the curve
    try:
        (mu, sigma), _ = curve_fit(psychometric_curve, x_data, y_data, p0=[0, 0.5])
        print(f"Block '{label}': PSE = {mu:.3f} | JND = {sigma:.3f}")
    except RuntimeError:
        print(f"Block '{label}': Optimal parameters not found.")
        continue

    x_fit = np.linspace(df['offset'].min(), df['offset'].max(), 100)

    p = plt.plot(x_fit, psychometric_curve(x_fit, mu, sigma), linestyle='-', label=f'{label} Fit (JND={sigma:.2f})')
    line_color = p[0].get_color()

    plt.scatter(x_data, y_data, color=line_color, alpha=0.6, label=f'{label} Data')

plt.xlabel('Offset ')
plt.ylabel('Proportion of "Right" Responses')
plt.title('Psychometric Function by Block')
plt.legend()
plt.grid(True)
plt.savefig('psychometric_function.png')
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from scipy.stats import norm

df = pd.read_csv('data_p7_session_01.csv')

df['offset_magnitude'] = df['offset'].abs()

def psychometric_curve_2afc(x, mu, sigma):
    # Scale to start at 0.5 (chance) and go to 1.0
    return 0.5 + 0.5 * norm.cdf(x, loc=mu, scale=sigma)

plt.figure(figsize=(10, 6))
print("--- Psychometric Function Fit Results ---")


for label, group in df.groupby('label'):
    summary = group.groupby('offset_magnitude')['accuracy'].apply(
        lambda x: x.astype(str).str.contains('correct').mean()
    ).reset_index(name='prob_correct')

    x_data = summary['offset_magnitude']
    y_data = summary['prob_correct']


    guess_mu = np.median(x_data)
    guess_sigma = (x_data.max() - x_data.min()) / 4.0

    try:
        (mu, sigma), _ = curve_fit(
            psychometric_curve_2afc,
            x_data,
            y_data,
            p0=[guess_mu, guess_sigma],
            maxfev=5000
        )
        print(f"Block '{label}': PSE = {mu:.3f} | JND = {sigma:.3f}")

    except RuntimeError:
        print(f"Block '{label}': Optimal parameters not found.")
        continue

    # Plotting Data Points and Fit Line
    # Create smooth x-values for the line starting from 0
    x_fit = np.linspace(0, df['offset_magnitude'].max(), 100)

    p = plt.plot(x_fit, psychometric_curve_2afc(x_fit, mu, sigma), linestyle='-', label=f'{label} Fit (JND={sigma:.4f})')
    line_color = p[0].get_color()

    plt.scatter(x_data, y_data, color=line_color, alpha=0.6)

# 3. Format and save the plot
plt.xlabel('Offset Magnitude (Absolute Value)')
plt.ylabel('Proportion of "correct" Responses')
plt.title('Accuracy Psychometric Function by Block (p7_session_02)')

# Move legend outside the plot so it doesn't cover the curves
plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True)
plt.tight_layout()
plt.savefig('psychometric_function_p7.png')
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import glob
import os

file_list = glob.glob('data_p*_session_*.csv')
file_list = [f for f in file_list if '(' not in f and '_parameters.csv' not in f]

# BINOCULAR DATA
results_binocular = []
for file in file_list:
    filename = os.path.basename(file)
    participant_id = filename.split('_')[1]
    indv_df = pd.read_csv(file)

    # CORRECT MATH: Absolute value FIRST so left/right don't cancel out
    indv_df['abs_offset'] = indv_df['offset'].abs()
    indv_L = indv_df.groupby('label')
    average_offsets = indv_L['abs_offset'].mean().reset_index()

    binocular_standard_offset = None
    binocular_crowded_offset = None

    # UPDATED: Using str.contains() to ignore block numbers
    standard_row = average_offsets[average_offsets['label'].str.contains('Binocular_Standard')]
    if not standard_row.empty:
        binocular_standard_offset = standard_row['abs_offset'].iloc[0]

    crowded_row = average_offsets[average_offsets['label'].str.contains('Binocular_Crowded')]
    if not crowded_row.empty:
        binocular_crowded_offset = crowded_row['abs_offset'].iloc[0]

    ratio1 = np.nan

    # SAFETY CHECK
    if (binocular_standard_offset is not None) and (binocular_crowded_offset is not None):
        if binocular_standard_offset != 0:
            ratio1 = binocular_crowded_offset / binocular_standard_offset

    results_binocular.append({
        'participant_file': os.path.basename(file),
        'participant_id': participant_id,
        'standard_offset': binocular_standard_offset,
        'crowded_offset': binocular_crowded_offset,
        'ratio': ratio1
    })

final_df_binocular = pd.DataFrame(results_binocular)
final_results_df_binocular = final_df_binocular.groupby('participant_id').mean(numeric_only=True).reset_index()


results_monocular = []
for file in file_list:
    filename = os.path.basename(file)
    participant_id = filename.split('_')[1]
    indv_df = pd.read_csv(file)

    # CORRECT MATH: Absolute value FIRST so left/right don't cancel out
    indv_df['abs_offset'] = indv_df['offset'].abs()
    indv_Z = indv_df.groupby('label')
    average_offsets = indv_Z['abs_offset'].mean().reset_index()

    Monocular_Standard_offset = None
    Monocular_Crowded_offset = None

    standard_row = average_offsets[average_offsets['label'].str.contains('Monocular_Standard')]
    if not standard_row.empty:
        Monocular_Standard_offset = standard_row['abs_offset'].iloc[0]

    crowded_row = average_offsets[average_offsets['label'].str.contains('Monocular_Crowded')]
    if not crowded_row.empty:
        Monocular_Crowded_offset = crowded_row['abs_offset'].iloc[0]

    ratio2 = np.nan

    # SAFETY CHECK
    if (Monocular_Standard_offset is not None) and (Monocular_Crowded_offset is not None):
        if Monocular_Standard_offset != 0:
            ratio2 = Monocular_Crowded_offset / Monocular_Standard_offset

    results_monocular.append({
        'participant_file': os.path.basename(file),
        'participant_id': participant_id,
        'standard_offset': Monocular_Standard_offset,
        'crowded_offset': Monocular_Crowded_offset,
        'ratio': ratio2
    })

final_df_monocular = pd.DataFrame(results_monocular)
final_results_df_monocular = final_df_monocular.groupby('participant_id').mean(numeric_only=True).reset_index()

print("--- Binocular Results ---")
print(final_results_df_binocular)
print("\n--- Monocular Results ---")
print(final_results_df_monocular)


# PLOTTING
df = pd.merge(final_results_df_monocular, final_results_df_binocular, on='participant_id', suffixes=('_m', '_b'))
lim = 2
fig, ax = plt.subplots(figsize=(7, 6))

ax.scatter(np.log(df['ratio_m']), np.log(df['ratio_b']), s=150, c='lightblue')

ax.plot([-lim, lim], [-lim, lim], color='gray', linestyle='--', label='y = x', zorder=1)
ax.set(xlim=(-lim, lim), ylim=(-lim, lim), xlabel='Log(Monocular Ratio)', ylabel='Log(Binocular Ratio)', title='Threshold Ratios: Binocular vs Monocular')
ax.grid(True, linestyle=':', alpha=0.7)
ax.legend(loc='upper left')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import glob
import os

file_list = glob.glob('data_p*_session_*.csv')
file_list = [f for f in file_list if '(' not in f and '_parameters.csv' not in f]

results = []

for file in file_list:
    filename = os.path.basename(file)
    participant_id = filename.split('_')[1]

    indv_df = pd.read_csv(file)
    indv_df['abs_offset'] = indv_df['offset'].abs()

    average_offsets = indv_df.groupby('label')['abs_offset'].mean().reset_index()

    # UPDATED: Use str.contains() to ignore block numbers
    def get_offset(label_substring):
        row = average_offsets[average_offsets['label'].str.contains(label_substring, na=False)]
        return row['abs_offset'].iloc[0] if not row.empty else None

    # UPDATED: Pass only the condition names, ignoring the "Block X: " part
    bin_standard = get_offset('Binocular_Standard')
    bin_crowded  = get_offset('Binocular_Crowded')
    mon_standard = get_offset('Monocular_Standard')
    mon_crowded  = get_offset('Monocular_Crowded')

    ratio_S = np.nan
    ratio_C = np.nan

    # standard
    if (bin_standard is not None) and (mon_standard is not None):
        if bin_standard != 0: # Added safety check from your second script
            ratio_S =  mon_standard / bin_standard

    # crowded
    if (bin_crowded is not None) and (mon_crowded is not None):
        if bin_crowded != 0: # Added safety check
            ratio_C = mon_crowded / bin_crowded

    results.append({
        'participant_file': filename,
        'participant_id': participant_id,
        'bin_standard_offset': bin_standard,
        'bin_crowded_offset': bin_crowded,
        'ratio_S': ratio_S,
        'mon_standard_offset': mon_standard,
        'mon_crowded_offset': mon_crowded,
        'ratio_C': ratio_C
    })

final_df = pd.DataFrame(results)
final_results_df = final_df.groupby('participant_id').mean(numeric_only=True).reset_index()

print(" Results")
print(final_results_df)


lim = 0.5
fig, ax = plt.subplots(figsize=(7, 6))

ax.scatter(np.log(final_results_df['ratio_S']), np.log(final_results_df['ratio_C']), s=150, c='lightblue')

ax.plot([-lim, lim], [-lim, lim], color='gray', linestyle='--', label='y = x')
ax.plot([0,0], [-lim, lim], color='gray', linestyle='-', label='x = 0')
ax.plot([-lim, lim], [0,0], color='gray', linestyle='-', label='y = 0')
ax.set(xlim=(-lim, lim), ylim=(-lim, lim), xlabel='Log(RATIO STANDARD)', ylabel='Log(RATIO CROWDED)', title='Threshold Ratios: STANDARD vs CROWDED')
ax.grid(True, linestyle=':', alpha=0.7)
ax.legend(loc='upper left')

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import glob
import os

filename = 'data_p6_session_01.csv'
df = pd.read_csv(filename)
correct_data = df[df['response_numeric'] == 1]



# file_list = glob.glob('data_p*_session_*.csv')
# file_list = [f for f in file_list if '(' not in f and '_parameters.csv' not in f]

# all_data = pd.concat([pd.read_csv(f) for f in file_list])
# # Fix: Create 'is_correct' column from 'response_numeric' after concatenation
# correct_data = all_data[all_data['response_numeric'] == 1]
# correct_percentage = correct_data['response_numeric'].mean() * 100


# print(f"correct Percentage: {correct_percentage}%")

# results = []

# for file in file_list:
#     filename = os.path.basename(file)
#     participant_id = filename.split('_')[1]

#     indv_df = pd.read_csv(file)
#     indv_df['abs_offset'] = indv_df['offset'].abs()

#     average_offsets = indv_df.groupby('label')['abs_offset'].mean().reset_index()

#     # UPDATED FUNCTION: Uses str.contains() to ignore the Block numbers
#     def get_offset(condition_name):
#         row = average_offsets[average_offsets['label'].str.contains(condition_name, na=False)]
#         return row['abs_offset'].iloc[0] if not row.empty else None

#     # UPDATED CALLS: Just ask for the condition name!
#     bin_standard = get_offset('Binocular_Standard')
#     bin_crowded  = get_offset('Binocular_Crowded')
#     mon_standard = get_offset('Monocular_Standard')
#     mon_crowded  = get_offset('Monocular_Crowded')

#     ratio_S = np.nan
#     ratio_C = np.nan

#     # standard
#     if (bin_standard is not None) and (mon_standard is not None):
#             ratio_S =  mon_standard / bin_standard
#     # crowded
#     if (bin_crowded is not None) and (mon_crowded is not None):
#             ratio_C = mon_crowded / bin_crowded

#     results.append({
#         'participant_file': filename,
#         'participant_id': participant_id,
#         'bin_standard_offset': bin_standard,
#         'bin_crowded_offset': bin_crowded,
#         'ratio_S': ratio_S,
#         'mon_standard_offset': mon_standard,
#         'mon_crowded_offset': mon_crowded,
#         'ratio_C': ratio_C
#     })

# final_df = pd.DataFrame(results)
# final_results_df = final_df.groupby('participant_id').mean(numeric_only=True).reset_index()

# print(" Results")
# print(final_results_df)

# # PLOTTING
# lim = 0.5
# fig, ax = plt.subplots(figsize=(7, 6))

# ax.scatter(np.log(final_results_df['ratio_S']), np.log(final_results_df['ratio_C']), s=150, c='lightblue')

# ax.plot([-lim, lim], [-lim, lim], color='gray', linestyle='--', label='y = x')
# ax.plot([0,0], [-lim, lim], color='gray', linestyle='-') # Removed duplicate legend label
# ax.plot([-lim, lim], [0,0], color='gray', linestyle='-') # Removed duplicate legend label

# ax.set(xlim=(-lim, lim), ylim=(-lim, lim), xlabel='Log(RATIO STANDARD)', ylabel='Log(RATIO CROWDED)', title='Threshold Ratios: STANDARD vs CROWDED')
# ax.grid(True, linestyle=':', alpha=0.7)
# ax.legend(loc='upper left')

# plt.tight_layout()
# plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import glob
import re
import numpy as np

def calculate_jnd_75(df_block):
    if df_block.empty:
        return np.nan

    # Convert 'correct'/'incorrect' strings into 1s and 0s
    df_block = df_block.copy()
    df_block['is_correct'] = (df_block['accuracy'] == 'correct').astype(int)
    df_block['abs_offset'] = df_block['offset'].abs()

    # Calculate proportion correct (mean accuracy) at each unique offset
    grouped = df_block.groupby('abs_offset')['is_correct'].mean().reset_index()
    grouped = grouped.sort_values('abs_offset')

    x = grouped['abs_offset'].values
    y = grouped['is_correct'].values

    if len(x) < 2:
        return np.nan # Need at least 2 points to interpolate

    # Linear interpolation to find exactly where y (accuracy) = 0.75
    for i in range(len(x) - 1):
        # Check if 0.75 falls between this point and the next point
        if (y[i] <= 0.75 <= y[i+1]) or (y[i] >= 0.75 >= y[i+1]):
            # If accuracy is identical, avoid division by zero
            if y[i+1] - y[i] == 0:
                return x[i]

            # y = mx + b (Find slope and intercept to solve for x at y=0.75)
            slope = (y[i+1] - y[i]) / (x[i+1] - x[i])
            intercept = y[i] - slope * x[i]
            x_75 = (0.75 - intercept) / slope
            return x_75

    # Fallbacks if the data never crosses 75%
    if min(y) >= 0.75:
        # If even the smallest offset is >= 75% accurate, return the smallest offset tested
        return x[0]
    if max(y) < 0.75:
        # If they never reached 75% accuracy, return NaN (or x[-1] if you prefer the max offset)
        return np.nan

    return np.nan


# --- 2. Find files, FILTER OUT duplicates with "(1)" and parameter files ---
raw_file_list = glob.glob('data_p*_session_*.csv')
file_list = [f for f in raw_file_list if '(' not in f and '_parameters.csv' not in f]

print(f"Found {len(file_list)} clean files to process.")

all_sessions_data = []

# --- 3. Loop through files and extract the 75% JND ---
for file in file_list:
    match = re.search(r'(p\d+)_session', file)
    participant = match.group(1) if match else "unknown"

    df = pd.read_csv(file)

    # Separate data into the 4 blocks
    b1 = df[df['label'] == 'Block 1: Binocular_Standard']
    b2 = df[df['label'] == 'Block 2: Binocular_Crowded']
    b3 = df[df['label'] == 'Block 3: Monocular_Standard']
    b4 = df[df['label'] == 'Block 4: Monocular_Crowded']

    # Calculate JND for each block
    all_sessions_data.append({
        'Participant': participant,
        'b_standard': calculate_jnd_75(b1),
        'b_crowded': calculate_jnd_75(b2),
        'm_standard': calculate_jnd_75(b3),
        'm_crowded': calculate_jnd_75(b4)
    })

# --- 4. Convert to DataFrame and Average the Sessions ---
results_df = pd.DataFrame(all_sessions_data)

# Group by Participant and calculate the mean
avg_df = results_df.groupby('Participant').mean().reset_index()

# Drop rows where everything is NaN
avg_df = avg_df.dropna(subset=['b_standard', 'b_crowded', 'm_standard', 'm_crowded'], how='all')

print("\n--- Averaged 75% JND Thresholds per Participant ---")
for index, row in avg_df.iterrows():
    print(f"Participant: {row['Participant']}")
    print(f"  Binocular: Standard={row['b_standard']:.4f}, Crowded={row['b_crowded']:.4f}")
    print(f"  Monocular: Standard={row['m_standard']:.4f}, Crowded={row['m_crowded']:.4f}")
print("---------------------------------------------------\n")

# --- 5. Plotting ---
plt.figure(figsize=(8, 7))

plt.scatter(avg_df['b_standard'], avg_df['b_crowded'], color='green', s=150, label='Binocular (Avg)', alpha=0.8)
plt.scatter(avg_df['m_standard'], avg_df['m_crowded'], color='red', s=150, label='Monocular (Avg)', alpha=0.8)

# Annotate each point with the Participant ID
for index, row in avg_df.iterrows():
    participant_id = row['Participant']

    if pd.notna(row['b_standard']) and pd.notna(row['b_crowded']):
        plt.annotate(participant_id, (row['b_standard'], row['b_crowded']),
                     textcoords="offset points", xytext=(0, 12), ha='center',
                     fontsize=10, fontweight='bold', color='darkgreen')

    if pd.notna(row['m_standard']) and pd.notna(row['m_crowded']):
        plt.annotate(participant_id, (row['m_standard'], row['m_crowded']),
                     textcoords="offset points", xytext=(0, 12), ha='center',
                     fontsize=10, fontweight='bold', color='darkred')

# Calculate max value dynamically to size the plot perfectly
all_values = pd.concat([avg_df['b_standard'], avg_df['b_crowded'], avg_df['m_standard'], avg_df['m_crowded']])
valid_values = all_values.dropna()

max_val = valid_values.max() if not valid_values.empty else 0.1
axis_limit = max_val * 1.2 if max_val > 0 else 0.1

# Add a diagonal dashed line (y=x)
plt.plot([0, axis_limit], [0, axis_limit], 'k--', alpha=1, label='Equal Thresholds (y=x)')

plt.xlim(0, axis_limit)
plt.ylim(0, axis_limit)

# Updated Labels!
plt.xlabel('75% JND Threshold (Standard)', fontsize=12)
plt.ylabel('75% JND Threshold (Crowded)', fontsize=12)
plt.title('Vernier 75% Thresholds: Crowded vs Standard', fontsize=14)

plt.grid(True, linestyle='--', alpha=0.6)
plt.legend(loc='upper left')
plt.tight_layout()
plt.savefig('vernier_jnd_results_with_labels.png', dpi=300, bbox_inches='tight')
plt.show()

import matplotlib.pyplot as plt
import pandas as pd
import glob
import numpy as np

file_list = glob.glob('data_p*_session_*.csv')
file_list = [f for f in file_list if '(' not in f and '_parameters.csv' not in f]

df_list = []
for file in file_list:
    indv_df = pd.read_csv(file)
    indv_last_20 = indv_df.groupby('label').tail(20)
    average_offsets = indv_last_20.groupby('label')['offset'].mean().abs().reset_index()
    df_list.append(average_offsets)

plt.figure(figsize=(8, 7))

#enumerate gives item and its position number in the list
global_max = 0
for i, df in enumerate(df_list):
    # Safely get the offset, assign np.nan if the block is not found
    binocular_standard_series = df[df['label'] == 'Block 1: Binocular_Standard']['offset']
    Binocular_Standard = binocular_standard_series.iloc[0] if not binocular_standard_series.empty else np.nan

    binocular_crowded_series = df[df['label'] == 'Block 2: Binocular_Crowded']['offset']
    Binocular_Crowded = binocular_crowded_series.iloc[0] if not binocular_crowded_series.empty else np.nan

    monocular_standard_series = df[df['label'] == 'Block 3: Monocular_Standard']['offset']
    Monocular_Standard = monocular_standard_series.iloc[0] if not monocular_standard_series.empty else np.nan

    monocular_crowded_series = df[df['label'] == 'Block 4: Monocular_Crowded']['offset']
    Monocular_Crowded = monocular_crowded_series.iloc[0] if not monocular_crowded_series.empty else np.nan

    # Filter out NaN values before calculating max, or max will always be NaN
    current_offsets = [o for o in [Binocular_Standard, Binocular_Crowded, Monocular_Standard, Monocular_Crowded] if pd.notna(o)]
    if current_offsets:
        current_max = max(current_offsets)
        global_max = max(global_max, current_max)

    b_label = 'Binocular' if i == 0 else ""
    m_label = 'Monocular' if i == 0 else ""

    # Only plot if both values are not NaN
    if pd.notna(Binocular_Standard) and pd.notna(Binocular_Crowded):
        plt.scatter(Binocular_Standard, Binocular_Crowded, color='lightblue', s=150, label=b_label)
    if pd.notna(Monocular_Standard) and pd.notna(Monocular_Crowded):
        plt.scatter(Monocular_Standard, Monocular_Crowded, color='pink', s=150, label=m_label)

axis_limit = global_max * 1.2 if global_max > 0 else 0.1

plt.xlim(0, axis_limit)
plt.ylim(0, axis_limit)

plt.xlabel('Average of last 20 trials (Standard)', fontsize=12)
plt.ylabel('Average of last 20 trials (Crowded)', fontsize=12)
plt.title('Vernier Thresholds: Crowded vs Standard', fontsize=14, fontweight='bold')

plt.grid(True, linestyle=':', alpha=0.7)
plt.legend(loc='upper left')

plt.show()

!pip install psignifit
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from scipy.stats import norm
import psignifit as ps

data = np.array([[0.0010, 45.0000, 90.0000], [0.0015, 50.0000, 90.0000],
                 [0.0020, 44.0000, 90.0000], [0.0025, 44.0000, 90.0000],
                 [0.0030, 52.0000, 90.0000], [0.0035, 53.0000, 90.0000],
                 [0.0040, 62.0000, 90.0000], [0.0045, 64.0000, 90.0000],
                 [0.0050, 76.0000, 90.0000], [0.0060, 79.0000, 90.0000],
                 [0.0070, 88.0000, 90.0000], [0.0080, 90.0000, 90.0000],
                 [0.0100, 90.0000, 90.0000]])

res = ps.psignifit(data, sigmoid='norm', experiment_type='2AFC')

# 1. Load data
df = pd.read_csv('data_p8_session_01.csv')

# 2. Psychometric Function Setup
def psychometric_curve(x, mu, sigma):
    return norm.cdf(x, loc=mu, scale=sigma)

plt.figure(figsize=(10, 6))
print("--- Psychometric Function Fit Results ---")

# Group by label to loop through blocks easily
for label, group in df.groupby('label'):
    summary = group.groupby('offset')['accuracy'].apply(
        lambda x: x.astype(str).str.contains('correct').mean()
    ).reset_index(name='prob_correct')

    x_data = summary['offset']
    y_data = summary['prob_correct']

    # Fit the curve
    try:
        (mu, sigma), _ = curve_fit(psychometric_curve, x_data, y_data, p0=[0, 0.5])
        print(f"Block '{label}': PSE = {mu:.3f} | JND = {sigma:.3f}")
    except RuntimeError:
        print(f"Block '{label}': Optimal parameters not found.")
        continue # Skip plotting the curve for this block if it fails

    # Plotting Data Points and Fit Line
    x_fit = np.linspace(df['offset'].min(), df['offset'].max(), 100)

    # Plot the line first, then grab its auto-assigned color for the scatter points
    p = plt.plot(x_fit, psychometric_curve(x_fit, mu, sigma), linestyle='-', label=f'{label} Fit (JND={sigma:.2f})')
    line_color = p[0].get_color()

    # Added alpha=0.6 to make overlapping points visible
    plt.scatter(x_data, y_data, color=line_color, alpha=0.6, label=f'{label} Data')

# 3. Format and save the plot
plt.xlabel('Offset ')
plt.ylabel('Proportion of "correct" Responses')
plt.title('Psychometric Function by Block')
plt.legend()
plt.grid(True)
plt.savefig('psychometric_function.png')
plt.show()